#!/bin/bash
#PBS -l nodes=2:ppn=12,walltime=00:01:00
#PBS -q batch
#PBS -N test_LA4
#PBS -j oe
#PBS -V

cd /home/smithn4/traffic_sim

export OMP_NUM_THREADS=4
mpiexec -np 2 --map-by ppr:1:node --hostfile $PBS_NODEFILE ./main.cx
mv *.grid files
mv *.speed files
